[package]
name = "core"
version = "0.1.0"
authors = ["Nikita Volobuev <nikitavbv@gmail.com>", "Pavlo Myroniuk <pspos.developqkation@gmail.com>"]
edition = "2018"

[dependencies]
libloading = "0.7.0"
custom_error = "1.8.0"
log = "0.4.0"
env_logger = "0.8.3"
regex = "1"