apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage-proxy
  namespace: turbocow
  labels:
    app: cloud-storage-proxy
spec:
  selector:
    matchLabels:
      app: cloud-storage-proxy
  replicas: 3
  template:
    metadata:
      labels:
        app: cloud-storage-proxy
    spec:
      containers:
      - name: cloud-storage-proxy
        image: pottava/s3-proxy:2.0
        ports:
        - containerPort: 80
        env:
        - name: AWS_S3_BUCKET
          value: turbocow
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: gcs-access-key
              key: gcs-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: gcs-secret-key
              key: gcs-secret-key
        - name: AWS_API_ENDPOINT
          value: https://storage.googleapis.com
        resources:
          limits:
            memory: 100M
            cpu: '250m'
          requests:
            memory: 5M
            cpu: '1m'
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-proxy
  namespace: turbocow
spec:
  selector:
    app: cloud-storage-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
