apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbocow-worker
spec:
  selector:
    matchLabels:
      app: turbocow-worker
  replicas: 2
  template:
    metadata:
      labels:
        app: turbocow-worker
    spec:
      containers:
      - name: turbocow-worker
        image: registry.gitlab.com/turbocow/turbocow/turbocow:0.1.224
        args: ['distributed', 'worker']
        env:
        - name: REDIS_ADDRESS
          value: 'redis'
        - name: METRICS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: metrics-config
              key: metrics_endpoint
        - name: METRICS_USERNAME
          valueFrom:
            secretKeyRef:
              name: metrics-auth
              key: username
        - name: METRICS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metrics-auth
              key: password
        resources:
          limits:
            memory: '1Gi'
            cpu: '1'
          requests:
            memory: '1Gi'
            cpu: '1'
