apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbocow-worker
spec:
  selector:
    matchLabels:
      app: turbocow-worker
  replicas: 0
  template:
    metadata:
      labels:
        app: turbocow-worker
    spec:
      containers:
      - name: turbocow-worker
        image: registry.gitlab.com/turbocow/turbocow/turbocow:0.1.223
        args: ['distributed', 'worker']
        env:
        - name: REDIS_ADDRESS
          value: 'redis'
        resources:
          limits:
            memory: '1Gi'
            cpu: '1'
          requests:
            memory: '1Gi'
            cpu: '1'
